steps:
  # Build the helloworld container image.
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/${PROJECT_ID}/node-hello"
      - "-f"
      - "./Dockerfile"
      - "."
images:
  - gcr.io/${PROJECT_ID}/node-hello

- name: "gcr.io/cloud-builders/gcloud"
  args: ['beta', 'run', 'deploy', 'dashboard', '--image', 'gcr.io/grove-staging/node-hello:latest', '--region', 'asia-east1', '--allow-unauthenticated', '--platform', 'managed']