steps:
  # Build the helloworld container image.
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/${PROJECT_ID}/node-hello:${TAG_NAME}"
      - "-f"
      - "./Dockerfile"
      - "."
